/*versionid=0x000D0010*/
/*maxGain=0.00*/
/*param0.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x06,
	/*reserved*/
	0x00,
}
,
/*param1.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
/*param2.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
/*param3.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
/*param4.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
/*param5.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
/*param6.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
/*param7.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
/*param8.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
/*param9.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
/*param10.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
/*param11.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
/*param12.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
/*param13.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
/*param14.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
/*param15.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
/*param16.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
/*param17.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
/*param18.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
/*param19.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
/*param20.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
/*param21.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
/*param22.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
/*param23.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
/*param24.&BasePoint=1&*/
/*n6pro_sensor_pyramid_offl_level*/
{
	/*dec_offline_bypass*/
	0x00,
	/*reconstruction_byass*/
	0x00,
	/*offline_layer_num*/
	0x00,
	/*reserved*/
	0x00,
}
,
