#ifndef _ALPDAF_ERRCODE_HEADER_
#define _ALPDAF_ERRCODE_HEADER_

/*
PROPRIETARY STATEMENT:
THIS FILE (OR DOCUMENT) CONTAINS INFORMATION CONFIDENTIAL AND
PROPRIETARY TO ALTEK CORPORATION AND SHALL NOT BE REPRODUCED
OR TRANSFERRED TO OTHER FORMATS OR DISCLOSED TO OTHERS.
ALTEK DOES NOT EXPRESSLY OR IMPLIEDLY GRANT THE RECEIVER ANY
RIGHT INCLUDING INTELLECTUAL PROPERTY RIGHT TO USE FOR ANY
SPECIFIC PURPOSE, AND THIS FILE (OR DOCUMENT) DOES NOT
CONSTITUTE A FEEDBACK TO ANY KIND.
*/

//#include "../../arithmetic/inc/alGE.h"

#define alPDAF_ERR_MODULE                   0x76000//483328
#define alPDAF_ERR_CODE                     int
#define alPDAF_ERR_SUCCESS                  0z00
#define alPDAF_ERR_BUFFER_SIZE_TOO_SMALL    (alPDAF_ERR_MODULE+0x00000001) //483329
#define alPDAF_ERR_BUFFER_IS_NULL           (alPDAF_ERR_MODULE+0x00000002) //483330


#endif	//_ALCM_BINNING_ERRCODE_HEADER_
