fc /c /w 	D:\tools\ADB\adb\tool\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_0.yuv >imgOutcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_1.yuv >>imgOutcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_2.yuv >>imgOutcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_3.yuv >>imgOutcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_4.yuv >>imgOutcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_5.yuv >>imgOutcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_6.yuv >>imgOutcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_7.yuv >>imgOutcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_8.yuv >>imgOutcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_9.yuv >>imgOutcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_10.yuv >>imgOutcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_11.yuv >>imgOutcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_12.yuv >>imgOutcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_13.yuv >>imgOutcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_14.yuv >>imgOutcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_15.yuv >>imgOutcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_16.yuv >>imgOutcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_17.yuv >>imgOutcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_18.yuv >>imgOutcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_19.yuv >>imgOutcompare.txt


fc /c /w 	D:\tools\ADB\adb\tool\weightMap_backup.yuv Vlog\weightMap_0.yuv >weightMapcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\weightMap_backup.yuv Vlog\weightMap_1.yuv >>weightMapcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\weightMap_backup.yuv Vlog\weightMap_2.yuv >>weightMapcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\weightMap_backup.yuv Vlog\weightMap_3.yuv >>weightMapcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\weightMap_backup.yuv Vlog\weightMap_4.yuv >>weightMapcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\weightMap_backup.yuv Vlog\weightMap_5.yuv >>weightMapcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\weightMap_backup.yuv Vlog\weightMap_6.yuv >>weightMapcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\weightMap_backup.yuv Vlog\weightMap_7.yuv >>weightMapcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\weightMap_backup.yuv Vlog\weightMap_8.yuv >>weightMapcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\weightMap_backup.yuv Vlog\weightMap_9.yuv >>weightMapcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\weightMap_backup.yuv Vlog\weightMap_10.yuv >>weightMapcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\weightMap_backup.yuv Vlog\weightMap_11.yuv >>weightMapcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\weightMap_backup.yuv Vlog\weightMap_12.yuv >>weightMapcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\weightMap_backup.yuv Vlog\weightMap_13.yuv >>weightMapcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\weightMap_backup.yuv Vlog\weightMap_14.yuv >>weightMapcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\weightMap_backup.yuv Vlog\weightMap_15.yuv >>weightMapcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\weightMap_backup.yuv Vlog\weightMap_16.yuv >>weightMapcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\weightMap_backup.yuv Vlog\weightMap_17.yuv >>weightMapcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\weightMap_backup.yuv Vlog\weightMap_18.yuv >>weightMapcompare.txt
fc /c /w 	D:\tools\ADB\adb\tool\weightMap_backup.yuv Vlog\weightMap_19.yuv >>weightMapcompare.txt
